---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: restore-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    mount:
    - ./node_modules
    restore: true
  volumes:
  - name: 2f746d702f6361636865
    path: /cache

- name: build
  pull: default
  image: patwie/elm-app
  commands:
  - node -v
  - npm -v
  - elm-app build

- name: test
  pull: default
  image: node:11.13.0
  commands:
  - "echo \"none\""

- name: rebuild-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    mount:
    - ./node_modules
    rebuild: true
  volumes:
  - name: 2f746d702f6361636865
    path: /cache

- name: create_release
  pull: default
  image: patwie/tar
  commands:
    - tar -czvf infomark-ui.tar.gz build/ README.md

- name: publish_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - infomark-ui.tar.gz
    checksum:
      - md5
      - sha256
  when:
    event: tag


volumes:
- name: 2f746d702f6361636865
  host:
    path: /tmp/cache

# ---
# kind: signature
# hmac: f89382f27cd2d9cb412622fc536e1d62f94832683339e3cb49d1ce9b321821a7
...
